/*
===============================================================================
                                Magnitude Analysis
===============================================================================
Purpose:        
    - To calculate total sales, counts, and averages across different parts of the business.
    - Highlights what drives our growth, which products are popular, and where our biggest markets are.

Key SQL Tools Used:        
    - Summary Functions: SUM() (Totals money/items), COUNT() (Counts rows), AVG() (Calculates averages)
    - GROUP BY: Combines individual rows into clean summary totals.
    - ORDER BY: Sorts results from highest to lowest (or vice versa) to instantly see top performers.
===============================================================================
*/

-- Switch to our main retail database to run these queries
USE RetailSalesAnalytics;
GO

-- ----------------------------------------------------------------------------- 
-- 1) Customer Location & Demographics
-- ----------------------------------------------------------------------------- 

-- Count how many customers live in each country
-- Shows where our biggest customer bases are located to help plan regional marketing and shipping.
SELECT 
    country, 
    COUNT(customer_id) AS total_customers
FROM dim_customers
GROUP BY country
ORDER BY total_customers DESC; -- Puts our largest geographical markets at the very top

-- Count customers by gender
-- Breaks down our customer base by gender to help marketing teams tailor their campaigns.
SELECT 
    gender, 
    COUNT(customer_id) AS total_customers
FROM dim_customers
GROUP BY gender
ORDER BY total_customers DESC;


-- ----------------------------------------------------------------------------- 
-- 2) Product Catalog Variety & Stock Breakdown
-- ----------------------------------------------------------------------------- 

-- Count the number of unique products in each category and subcategory
-- Measures the size and variety of our catalog to see where our product selection is wide or narrow.
-- This helps inventory managers understand which collections offer the most options to shoppers.
SELECT 
    category, 
    subcategory, 
    COUNT(product_id) AS unique_products_count
FROM dim_products
GROUP BY category, subcategory
ORDER BY category, unique_products_count DESC;

-- ----------------------------------------------------------------------------- 
-- 3) Sales & Order Performance by Region
-- ----------------------------------------------------------------------------- 

-- Count the total number of orders placed by each country
-- Measures customer order volume per country by counting unique invoice numbers.
SELECT
    c.country,
    COUNT(DISTINCT f.order_number) AS total_orders
FROM fact_sales f
LEFT JOIN dim_customers c ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_orders DESC;

-- Calculate total revenue generated by each country
-- This shows us if our highest-volume countries are also bringing in the most money.
SELECT
    c.country,
    SUM(f.sales_amount) AS total_sales_amount
FROM fact_sales f
LEFT JOIN dim_customers c ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_sales_amount DESC;

-- ----------------------------------------------------------------------------- 
-- 4) Product Performance & Sales Insights
-- ----------------------------------------------------------------------------- 

-- Calculate total revenue generated by each product 
-- Maps sales across categories and subcategories to find our top money-making items.
-- This groups items by their entire catalog path so we can spot high-value trends.
SELECT
    p.product_line,
    p.category,
    p.subcategory,
    p.product_name,
    SUM(f.sales_amount) AS total_sales_amount
FROM fact_sales f
LEFT JOIN dim_products p ON f.product_key = p.product_key
GROUP BY 
    p.category,
    p.subcategory,
    p.product_line,
    p.product_name
ORDER BY total_sales_amount DESC;

-- List products that were actually sold and how many times each was sold
-- Uses an INNER JOIN to look strictly at active products and order them by popular demand.
-- This highlights our fastest-moving store inventory.
SELECT 
    p.product_name,
    p.category,
    p.subcategory,
    COUNT(*) AS times_sold
FROM fact_sales f
INNER JOIN dim_products p ON f.product_key = p.product_key
GROUP BY 
    p.product_name,
    p.category,
    p.subcategory
ORDER BY times_sold DESC;

-- List products that have never been sold
-- Uses a LEFT JOIN and a HAVING filter to pinpoint items with zero sales traffic.
-- This helps management identify dead stock that is taking up valuable warehouse space.
SELECT 
    p.product_name,
    p.category,
    p.subcategory
FROM dim_products p
LEFT JOIN fact_sales f ON p.product_key = f.product_key
GROUP BY 
    p.product_name,
    p.category,
    p.subcategory
HAVING COUNT(f.product_key) = 0
ORDER BY p.category, p.product_name;

-- Show sold and unsold products side-by-side
-- Combines our active and inactive inventory into a single summary view.
-- Uses conditional CASE WHEN logic to stamp a clear 'Sold' or 'Unsold' label on each item.
SELECT 
    p.product_name,
    p.category,
    p.subcategory,
    COUNT(f.product_key) AS times_sold,
    CASE 
        WHEN COUNT(f.product_key) = 0 THEN 'Unsold'
        ELSE 'Sold'
    END AS product_status
FROM dim_products p
LEFT JOIN fact_sales f ON p.product_key = f.product_key
GROUP BY 
    p.product_name,
    p.category,
    p.subcategory
ORDER BY product_status DESC, times_sold DESC;


-- ----------------------------------------------------------------------------- 
-- 5) Business Revenue & Customer Spending Analysis
-- ----------------------------------------------------------------------------- 

-- Calculate the average product cost in each category
-- Looks at what we pay to acquire or make these goods to find where our inventory expenses are highest.
SELECT
    category,
    AVG(cost) AS avg_cost
FROM dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- Calculate total revenue generated by each product category
-- Compares sales across major categories to see which product group brings in the most money.
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM fact_sales f
LEFT JOIN dim_products p ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Calculate the total revenue generated by each customer
-- Summarizes individual lifetime spending to spot our high-value loyal buyers.
-- Sorting by highest revenue lets us quickly see who our most valuable shoppers are.
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM fact_sales f
LEFT JOIN dim_customers c ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- Find the total number of items sold across different countries
-- Sums up the physical quantities purchased to measure product distribution worldwide.
-- This helps our supply chain team understand shipping volumes needed for each country.
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM fact_sales f
LEFT JOIN dim_customers c ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;